### PR TITLE
Edits to get the code to work with 7.4.2 and allow multiple classes

### PR DESCRIPTION
**Pull request by protherj**
- Changed from usky- to umb-
- Dealt with the -active classes
- Allowed more than one class element
- Swapped the order of the styles and attributes to allow for customization of styles based on attributes if needed

### CODE REVIEW

**Comment by hyrmedia** [comment]
I'd really like to see this merged..

**Comment by hyrmedia** [comment]
Any chance of getting this merged and updated on Nuget soon?

**Comment by agiraud** [comment]
Thanks @protherj !

**Comment by hyrmedia** [comment]
When will this be updated on Nuget?

**Pull request merged**
